/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as LoginImport } from './pages/login'
import { Route as LayoutImport } from './pages/_layout'
import { Route as R404Import } from './pages/__404'
import { Route as LayoutIndexImport } from './pages/_layout/index'
import { Route as LayoutUserImport } from './pages/_layout/user'
import { Route as LayoutCreditImport } from './pages/_layout/credit'
import { Route as LayoutClientImport } from './pages/_layout/client'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/__404',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUserRoute = LayoutUserImport.update({
  path: '/user',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCreditRoute = LayoutCreditImport.update({
  path: '/credit',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClientRoute = LayoutClientImport.update({
  path: '/client',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__404': {
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/client': {
      preLoaderRoute: typeof LayoutClientImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/credit': {
      preLoaderRoute: typeof LayoutCreditImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/user': {
      preLoaderRoute: typeof LayoutUserImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  R404Route,
  LayoutRoute.addChildren([
    LayoutClientRoute,
    LayoutCreditRoute,
    LayoutUserRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
